import type { Metadata } from "next";
import '../styles/global.css';
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-100 antialiased">
        {children}
      </body>
    </html>
  );
}
