import Sidebar from '@/components/dashboard/sidebar/Sidebar';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="flex h-screen bg-gray-100">
            <Sidebar />
            <div className="flex-1 transition-all duration-200 ease-in-out">
                <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-100">
                    <div className="w-full px-6 py-8">{children}</div>
                </main>
            </div>
        </div>
    );
}
